# Generated by Django 4.2.1 on 2023-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
