# Generated by Django 4.2.1 on 2023-05-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_musica', '0003_rename_generos_cancion_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
