# Generated by Django 4.2.1 on 2023-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_musica', '0004_rename_usuario_perfilusuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, verbose_name='Apellidos')),
                ('imagen_perfil', models.ImageField(default='default_perfil.png', upload_to='usuarios')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=250, verbose_name='Password')),
                ('biblioteca', models.ManyToManyField(to='api_musica.cancion')),
            ],
        ),
    ]
